---
- name: Set epel-release package name for RHEL
  ansible.builtin.set_fact:
    epel_package:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_distribution == "RedHat"

- name: Install the distribution's epel-release package
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: "{{ epel_package }}"
  retries: 3
  delay: 5
  register: install
  until: install is succeeded

- name: Enable the EPEL repository
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.command:
    argv:
      - "/usr/bin/dnf"
      - "config-manager"
      - "--enable"
      - "{{ 'ol' + ansible_distribution_major_version + '_developer_EPEL' }}"
  register: enable
  changed_when: enable is succeeded
  when:
    - ansible_distribution == "OracleLinux"
