---
nfsd_packages:
  - lvm2
  - nfs-utils
  - policycoreutils

krb5_packages:
  - gssproxy
  - libverto-libev1

fstype_userspace_progs:
  btrfs: btrfsprogs
  ext4: e2fsprogs
  xfs: xfsprogs

pipefs_directory: /var/lib/nfs/rpc_pipefs
