---
- name: Enable a CodeReady Builder repo for this distribution
  when:
    - ansible_distribution != "Fedora"
    - not devconfig_custom_yum_repofile
  block:
    - name: Select the RHEL CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
      when:
        - ansible_distribution == 'RedHat'
        - kdevops_enable_guestfs

    - name: Select the Oracle Linux CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "ol9_codeready_builder"
      when:
        - ansible_distribution == 'OracleLinux'

    - name: Select the CentOS CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "crb"
      when:
        - ansible_distribution == 'CentOS'

    - name: Select the AWS RHEL CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-rhui-rpms"
      when:
        - ansible_distribution == 'RedHat'
        - kdevops_enable_terraform
        - kdevops_terraform_provider == "aws"

    - name: Select the Azure RHEL CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rhui-rpms"
      when:
        - ansible_distribution == 'RedHat'
        - kdevops_enable_terraform
        - kdevops_terraform_provider == "azure"

    - name: Select the Google Cloud RHEL CodeReady Builder repo
      ansible.builtin.set_fact:
        codeready_repo: "rhui-codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rhui-rpms"
      when:
        - ansible_distribution == 'RedHat'
        - kdevops_enable_terraform
        - kdevops_terraform_provider == "gce"

    - name: The distribution/provisioner combo isn't recognized
      ansible.builtin.fail:
        msg: The selection heuristic failed to find a CodeReady Builder repo.
      when:
        - codeready_repo is not defined

    - name: Enable the selected CodeReady Builder repo
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.command:
        argv:
          - "/usr/bin/dnf"
          - "config-manager"
          - "--enable"
          - "{{ codeready_repo }}"
      register: dnf_result
      changed_when: dnf_result is success
