---
# Only run mirror checks for Debian testing (trixie) where mirror issues are common
- name: Check for DEB822-style sources
  stat:
    path: /etc/apt/sources.list.d/debian.sources
  register: deb822_sources

- name: Extract current APT mirror hostname (DEB822 format)
  shell: |
    grep -E "^URIs:" /etc/apt/sources.list.d/debian.sources | head -1 | awk '{print $2}' | sed -E 's|https?://||' | cut -d'/' -f1
  register: apt_mirror_host_deb822
  changed_when: false
  ignore_errors: yes
  when: deb822_sources.stat.exists

- name: Extract current APT mirror hostname (legacy format)
  shell: |
    grep -E "^deb\s+http" /etc/apt/sources.list | head -1 | awk '{print $2}' | sed 's|http://||' | cut -d'/' -f1
  register: apt_mirror_host_legacy
  changed_when: false
  ignore_errors: yes
  when: not deb822_sources.stat.exists

- name: Set unified mirror hostname
  set_fact:
    apt_mirror_host:
      stdout: "{{ apt_mirror_host_deb822.stdout if deb822_sources.stat.exists else apt_mirror_host_legacy.stdout }}"

- name: Check connectivity to current APT mirror
  wait_for:
    host: "{{ apt_mirror_host.stdout }}"
    port: 80
    timeout: 10
  register: mirror_connectivity
  ignore_errors: yes
  when: apt_mirror_host.stdout != ""

- name: Display mirror check results
  debug:
    msg: |
      Current APT mirror: {{ apt_mirror_host.stdout | default('Not found') }}
      Mirror connectivity: {{ 'OK' if mirror_connectivity is not failed else 'FAILED' }}
  when: apt_mirror_host.stdout != ""

- name: Fall back to official Debian mirrors if current mirror fails
  block:
    - name: Backup current sources (DEB822 format)
      copy:
        src: /etc/apt/sources.list.d/debian.sources
        dest: /etc/apt/sources.list.d/debian.sources.backup
        remote_src: yes
      become: yes
      when: deb822_sources.stat.exists

    - name: Backup current sources (legacy format)
      copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list.backup
        remote_src: yes
      become: yes
      when: not deb822_sources.stat.exists

    - name: Apply Debian testing fallback sources using modern DEB822 format
      template:
        src: debian-testing-fallback.sources
        dest: /etc/apt/sources.list.d/debian.sources
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Remove legacy sources.list if migrating to DEB822
      file:
        path: /etc/apt/sources.list
        state: absent
      become: yes
      when: not deb822_sources.stat.exists

    - name: Update APT cache after mirror change
      apt:
        update_cache: yes
        cache_valid_time: 0
      become: yes

    - name: Inform user about mirror fallback
      debug:
        msg: |
          WARNING: The configured APT mirror '{{ apt_mirror_host.stdout }}' is not accessible.
          Falling back to official Debian testing mirrors using modern DEB822 format:
          - deb.debian.org for main packages
          - security.debian.org for security updates

          Your sources have been migrated to /etc/apt/sources.list.d/debian.sources
          This may result in slower package downloads depending on your location.
          Consider configuring a local mirror for better performance.

  when:
    - apt_mirror_host.stdout != ""
    - mirror_connectivity is failed
