---
- name: Set up an LVM for guestfs
  ansible.builtin.include_tasks:
    file: guestfs.yml
  when:
    - kdevops_enable_guestfs|bool

- name: Set up an LVM for terraform
  ansible.builtin.include_tasks:
    file: terraform.yml
  when:
    - kdevops_enable_terraform|bool
