---
- name: Gather the list of running libvirt guests
  run_once: true
  community.libvirt.virt:
    command: list_vms
    state: running
    uri: "{{ libvirt_uri }}"
  register: running_vms

- name: Shut down each running target node
  community.libvirt.virt:
    name: "{{ inventory_hostname }}"
    command: destroy
    uri: "{{ libvirt_uri }}"
  changed_when: true
  when:
    - inventory_hostname in running_vms.list_vms

- name: Gather the list of stopped libvirt guests
  run_once: true
  community.libvirt.virt:
    command: list_vms
    state: shutdown
    uri: "{{ libvirt_uri }}"
  register: shutdown_vms

- name: Undefine each stopped target node
  community.libvirt.virt:
    command: "undefine"
    force: true
    name: "{{ inventory_hostname }}"
    uri: "{{ libvirt_uri }}"
  changed_when: true
  when:
    - inventory_hostname in shutdown_vms.list_vms

- name: Remove per-node configuration files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ guestfs_path }}/{{ inventory_hostname }}"
    - "{{ kdevops_storage_pool_path }}/guestfs/{{ inventory_hostname }}"

- name: Remove global configuration files
  run_once: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ kdevops_ssh_config }}"
    - "{{ topdir_path }}/{{ kdevops_nodes }}"
