---
- name: Run fio performance tests
  hosts:
    - baseline
    - dev
  become: false
  vars:
    ansible_ssh_pipelining: true
  roles:
    - role: create_data_partition
      tags: ["data_partition"]
    - role: fio-tests
