---
- name: Save fio test results as baseline
  hosts:
    - baseline
    - dev
  become: false
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - name: Create baseline directory structure
      ansible.builtin.file:
        path: "{{ fio_tests_results_dir }}/baseline"
        state: directory
        mode: "0755"
      become: true

    - name: Save current test configuration as baseline
      ansible.builtin.copy:
        src: "{{ fio_tests_results_dir }}/results_{{ item }}.txt"
        dest: "{{ fio_tests_results_dir }}/baseline/baseline_{{ item }}.txt"
        remote_src: true
        backup: true
        mode: "0644"
      with_fileglob:
        - "{{ fio_tests_results_dir }}/results_*.txt"
      become: true
      failed_when: false

    - name: Create baseline timestamp
      ansible.builtin.shell: date > "{{ fio_tests_results_dir }}/baseline/baseline_timestamp.txt"
      become: true
      changed_when: true
