---
- hosts: all
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  tasks:
    - name: Import optional extra_args file
      include_vars: "{{ item }}"
      ignore_errors: yes
      with_first_found:
        - files:
          - "../extra_vars.yml"
          - "../extra_vars.yaml"
          - "../extra_vars.json"
          skip: true
      tags: vars

    - name: Collect monitoring results without stopping monitoring
      include_role:
        name: monitoring
        tasks_from: monitor_collect_only
      when:
        - enable_monitoring|default(false)|bool
      tags: [ 'monitoring', 'monitor_collect' ]
